# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pygisedtrend_text_file_analysis.ui'
#
# Created: Mon Aug 10 11:31:03 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_pygisedtrend_text_file_analysis(object):
    def setupUi(self, pygisedtrend_text_file_analysis):
        pygisedtrend_text_file_analysis.setObjectName(_fromUtf8("pygisedtrend_text_file_analysis"))
        pygisedtrend_text_file_analysis.resize(688, 472)
        self.buttonBox = QtGui.QDialogButtonBox(pygisedtrend_text_file_analysis)
        self.buttonBox.setGeometry(QtCore.QRect(330, 430, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.groupBox = QtGui.QGroupBox(pygisedtrend_text_file_analysis)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 621, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioSpace = QtGui.QRadioButton(self.groupBox)
        self.radioSpace.setGeometry(QtCore.QRect(20, 30, 86, 22))
        self.radioSpace.setChecked(True)
        self.radioSpace.setObjectName(_fromUtf8("radioSpace"))
        self.radioTabulation = QtGui.QRadioButton(self.groupBox)
        self.radioTabulation.setGeometry(QtCore.QRect(120, 30, 120, 22))
        self.radioTabulation.setObjectName(_fromUtf8("radioTabulation"))
        self.radioComma = QtGui.QRadioButton(self.groupBox)
        self.radioComma.setGeometry(QtCore.QRect(260, 30, 104, 22))
        self.radioComma.setObjectName(_fromUtf8("radioComma"))
        self.radioSimilicon = QtGui.QRadioButton(self.groupBox)
        self.radioSimilicon.setGeometry(QtCore.QRect(390, 30, 113, 22))
        self.radioSimilicon.setObjectName(_fromUtf8("radioSimilicon"))
        self.radioPipe = QtGui.QRadioButton(self.groupBox)
        self.radioPipe.setGeometry(QtCore.QRect(510, 30, 84, 22))
        self.radioPipe.setObjectName(_fromUtf8("radioPipe"))
        self.radioOther = QtGui.QRadioButton(self.groupBox)
        self.radioOther.setGeometry(QtCore.QRect(21, 63, 86, 22))
        self.radioOther.setObjectName(_fromUtf8("radioOther"))
        self.lineEditOther = QtGui.QLineEdit(self.groupBox)
        self.lineEditOther.setEnabled(False)
        self.lineEditOther.setGeometry(QtCore.QRect(113, 61, 129, 27))
        self.lineEditOther.setObjectName(_fromUtf8("lineEditOther"))
        self.groupBox_2 = QtGui.QGroupBox(pygisedtrend_text_file_analysis)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 130, 631, 80))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.widget = QtGui.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(12, 30, 610, 31))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBoxHeader = QtGui.QCheckBox(self.widget)
        self.checkBoxHeader.setObjectName(_fromUtf8("checkBoxHeader"))
        self.horizontalLayout_2.addWidget(self.checkBoxHeader)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.spinBoxSkipLine = QtGui.QSpinBox(self.widget)
        self.spinBoxSkipLine.setObjectName(_fromUtf8("spinBoxSkipLine"))
        self.horizontalLayout.addWidget(self.spinBoxSkipLine)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.checkBoxCommaSeparator = QtGui.QCheckBox(self.widget)
        self.checkBoxCommaSeparator.setObjectName(_fromUtf8("checkBoxCommaSeparator"))
        self.horizontalLayout_2.addWidget(self.checkBoxCommaSeparator)
        self.tableAnalysisResult = QtGui.QTableWidget(pygisedtrend_text_file_analysis)
        self.tableAnalysisResult.setGeometry(QtCore.QRect(30, 270, 641, 151))
        self.tableAnalysisResult.setObjectName(_fromUtf8("tableAnalysisResult"))
        self.tableAnalysisResult.setColumnCount(0)
        self.tableAnalysisResult.setRowCount(0)
        self.layoutWidget = QtGui.QWidget(pygisedtrend_text_file_analysis)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 210, 91, 52))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.comboBoxX = QtGui.QComboBox(self.layoutWidget)
        self.comboBoxX.setObjectName(_fromUtf8("comboBoxX"))
        self.verticalLayout.addWidget(self.comboBoxX)
        self.layoutWidget1 = QtGui.QWidget(pygisedtrend_text_file_analysis)
        self.layoutWidget1.setGeometry(QtCore.QRect(140, 210, 91, 52))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.comboBoxY = QtGui.QComboBox(self.layoutWidget1)
        self.comboBoxY.setObjectName(_fromUtf8("comboBoxY"))
        self.verticalLayout_2.addWidget(self.comboBoxY)
        self.layoutWidget2 = QtGui.QWidget(pygisedtrend_text_file_analysis)
        self.layoutWidget2.setGeometry(QtCore.QRect(250, 210, 91, 52))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.comboBoxZ = QtGui.QComboBox(self.layoutWidget2)
        self.comboBoxZ.setObjectName(_fromUtf8("comboBoxZ"))
        self.verticalLayout_3.addWidget(self.comboBoxZ)
        self.layoutWidget3 = QtGui.QWidget(pygisedtrend_text_file_analysis)
        self.layoutWidget3.setGeometry(QtCore.QRect(360, 210, 91, 52))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.comboBoxMean = QtGui.QComboBox(self.layoutWidget3)
        self.comboBoxMean.setObjectName(_fromUtf8("comboBoxMean"))
        self.verticalLayout_4.addWidget(self.comboBoxMean)
        self.layoutWidget4 = QtGui.QWidget(pygisedtrend_text_file_analysis)
        self.layoutWidget4.setGeometry(QtCore.QRect(470, 210, 91, 52))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_7 = QtGui.QLabel(self.layoutWidget4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.comboBoxSorting = QtGui.QComboBox(self.layoutWidget4)
        self.comboBoxSorting.setObjectName(_fromUtf8("comboBoxSorting"))
        self.verticalLayout_5.addWidget(self.comboBoxSorting)
        self.layoutWidget5 = QtGui.QWidget(pygisedtrend_text_file_analysis)
        self.layoutWidget5.setGeometry(QtCore.QRect(580, 210, 91, 52))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_8 = QtGui.QLabel(self.layoutWidget5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_6.addWidget(self.label_8)
        self.comboBoxSkewness = QtGui.QComboBox(self.layoutWidget5)
        self.comboBoxSkewness.setObjectName(_fromUtf8("comboBoxSkewness"))
        self.verticalLayout_6.addWidget(self.comboBoxSkewness)

        self.retranslateUi(pygisedtrend_text_file_analysis)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), pygisedtrend_text_file_analysis.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), pygisedtrend_text_file_analysis.reject)
        QtCore.QObject.connect(self.radioOther, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEditOther.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(pygisedtrend_text_file_analysis)

    def retranslateUi(self, pygisedtrend_text_file_analysis):
        pygisedtrend_text_file_analysis.setWindowTitle(_translate("pygisedtrend_text_file_analysis", "Dialog", None))
        self.groupBox.setTitle(_translate("pygisedtrend_text_file_analysis", "Separator", None))
        self.radioSpace.setText(_translate("pygisedtrend_text_file_analysis", "Space ( )", None))
        self.radioTabulation.setText(_translate("pygisedtrend_text_file_analysis", "Tabulation (t)", None))
        self.radioComma.setText(_translate("pygisedtrend_text_file_analysis", "Comma ( , )", None))
        self.radioSimilicon.setText(_translate("pygisedtrend_text_file_analysis", "Similicon ( ; )", None))
        self.radioPipe.setText(_translate("pygisedtrend_text_file_analysis", "Pipe ( | )", None))
        self.radioOther.setText(_translate("pygisedtrend_text_file_analysis", "Other(s)", None))
        self.groupBox_2.setTitle(_translate("pygisedtrend_text_file_analysis", "Line treatments", None))
        self.checkBoxHeader.setText(_translate("pygisedtrend_text_file_analysis", "First line as header", None))
        self.label.setText(_translate("pygisedtrend_text_file_analysis", "Skip", None))
        self.label_2.setText(_translate("pygisedtrend_text_file_analysis", "line(s)", None))
        self.checkBoxCommaSeparator.setText(_translate("pygisedtrend_text_file_analysis", "Comma decimal separator", None))
        self.label_3.setText(_translate("pygisedtrend_text_file_analysis", "X", None))
        self.label_4.setText(_translate("pygisedtrend_text_file_analysis", "Y", None))
        self.label_5.setText(_translate("pygisedtrend_text_file_analysis", "Z", None))
        self.label_6.setText(_translate("pygisedtrend_text_file_analysis", "Mean", None))
        self.label_7.setText(_translate("pygisedtrend_text_file_analysis", "Sorting", None))
        self.label_8.setText(_translate("pygisedtrend_text_file_analysis", "Skewness", None))

