# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pygisedtrend.ui'
#
# Created: Tue Aug  4 10:29:45 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_pygisedtrend(object):
    def setupUi(self, pygisedtrend):
        pygisedtrend.setObjectName(_fromUtf8("pygisedtrend"))
        pygisedtrend.resize(700, 600)
        pygisedtrend.setMaximumSize(QtCore.QSize(700, 600))
        pygisedtrend.setModal(True)
        self.buttonBox = QtGui.QDialogButtonBox(pygisedtrend)
        self.buttonBox.setGeometry(QtCore.QRect(490, 560, 201, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabDlg = QtGui.QTabWidget(pygisedtrend)
        self.tabDlg.setGeometry(QtCore.QRect(0, 0, 701, 531))
        self.tabDlg.setStyleSheet(_fromUtf8(""))
        self.tabDlg.setObjectName(_fromUtf8("tabDlg"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 160, 651, 181))
        self.label.setText(_fromUtf8(""))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/pygisedtrend/logogeoceano transparent.png")))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(120, 10, 421, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(210, 110, 241, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setPointSize(16)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 410, 371, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans"))
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 400, 66, 17))
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(410, 409, 241, 31))
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.tabDlg.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 671, 81))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.pushButtonTextFile = QtGui.QPushButton(self.groupBox_6)
        self.pushButtonTextFile.setGeometry(QtCore.QRect(180, 30, 95, 27))
        self.pushButtonTextFile.setObjectName(_fromUtf8("pushButtonTextFile"))
        self.GSTATemporaryLayerButton = QtGui.QPushButton(self.groupBox_6)
        self.GSTATemporaryLayerButton.setGeometry(QtCore.QRect(350, 30, 263, 27))
        self.GSTATemporaryLayerButton.setObjectName(_fromUtf8("GSTATemporaryLayerButton"))
        self.pushButtonDeteleRow = QtGui.QPushButton(self.tab_3)
        self.pushButtonDeteleRow.setGeometry(QtCore.QRect(21, 450, 92, 27))
        self.pushButtonDeteleRow.setObjectName(_fromUtf8("pushButtonDeteleRow"))
        self.layoutWidget = QtGui.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 80, 681, 351))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_4.addWidget(self.label_11)
        self.tableWidgetData = QtGui.QTableWidget(self.layoutWidget)
        self.tableWidgetData.setObjectName(_fromUtf8("tableWidgetData"))
        self.tableWidgetData.setColumnCount(0)
        self.tableWidgetData.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidgetData)
        self.pushButtonShapefile = QtGui.QPushButton(self.tab_3)
        self.pushButtonShapefile.setGeometry(QtCore.QRect(21, 40, 92, 27))
        self.pushButtonShapefile.setObjectName(_fromUtf8("pushButtonShapefile"))
        self.tabDlg.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.characteristicDistance = QtGui.QLineEdit(self.tab_2)
        self.characteristicDistance.setGeometry(QtCore.QRect(11, 41, 151, 27))
        self.characteristicDistance.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.characteristicDistance.setObjectName(_fromUtf8("characteristicDistance"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 171, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 341, 241))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.caseListEdit = QtGui.QTextEdit(self.groupBox)
        self.caseListEdit.setEnabled(True)
        self.caseListEdit.setGeometry(QtCore.QRect(10, 61, 81, 141))
        self.caseListEdit.setReadOnly(True)
        self.caseListEdit.setObjectName(_fromUtf8("caseListEdit"))
        self.buttonRemoveTrendCase = QtGui.QPushButton(self.groupBox)
        self.buttonRemoveTrendCase.setGeometry(QtCore.QRect(100, 141, 41, 27))
        self.buttonRemoveTrendCase.setObjectName(_fromUtf8("buttonRemoveTrendCase"))
        self.buttonAddTrendCase = QtGui.QPushButton(self.groupBox)
        self.buttonAddTrendCase.setGeometry(QtCore.QRect(100, 91, 41, 27))
        self.buttonAddTrendCase.setObjectName(_fromUtf8("buttonAddTrendCase"))
        self.trendMean = QtGui.QGroupBox(self.groupBox)
        self.trendMean.setGeometry(QtCore.QRect(150, 40, 181, 51))
        self.trendMean.setObjectName(_fromUtf8("trendMean"))
        self.trendSorting = QtGui.QGroupBox(self.groupBox)
        self.trendSorting.setGeometry(QtCore.QRect(150, 101, 181, 51))
        self.trendSorting.setObjectName(_fromUtf8("trendSorting"))
        self.trendSkewness = QtGui.QGroupBox(self.groupBox)
        self.trendSkewness.setGeometry(QtCore.QRect(150, 161, 181, 51))
        self.trendSkewness.setObjectName(_fromUtf8("trendSkewness"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(160, 60, 161, 24))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioMeanFiner = QtGui.QRadioButton(self.layoutWidget1)
        self.radioMeanFiner.setObjectName(_fromUtf8("radioMeanFiner"))
        self.horizontalLayout.addWidget(self.radioMeanFiner)
        self.radioMeanCoarser = QtGui.QRadioButton(self.layoutWidget1)
        self.radioMeanCoarser.setObjectName(_fromUtf8("radioMeanCoarser"))
        self.horizontalLayout.addWidget(self.radioMeanCoarser)
        self.radioMeanNone = QtGui.QRadioButton(self.layoutWidget1)
        self.radioMeanNone.setChecked(True)
        self.radioMeanNone.setObjectName(_fromUtf8("radioMeanNone"))
        self.horizontalLayout.addWidget(self.radioMeanNone)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(160, 120, 162, 24))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioSortingBetter = QtGui.QRadioButton(self.layoutWidget2)
        self.radioSortingBetter.setObjectName(_fromUtf8("radioSortingBetter"))
        self.horizontalLayout_2.addWidget(self.radioSortingBetter)
        self.radioSortingPorer = QtGui.QRadioButton(self.layoutWidget2)
        self.radioSortingPorer.setObjectName(_fromUtf8("radioSortingPorer"))
        self.horizontalLayout_2.addWidget(self.radioSortingPorer)
        self.radioSortingNone = QtGui.QRadioButton(self.layoutWidget2)
        self.radioSortingNone.setChecked(True)
        self.radioSortingNone.setObjectName(_fromUtf8("radioSortingNone"))
        self.horizontalLayout_2.addWidget(self.radioSortingNone)
        self.layoutWidget3 = QtGui.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(161, 180, 157, 24))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioSkewnessPositive = QtGui.QRadioButton(self.layoutWidget3)
        self.radioSkewnessPositive.setObjectName(_fromUtf8("radioSkewnessPositive"))
        self.horizontalLayout_3.addWidget(self.radioSkewnessPositive)
        self.radioSkewnessNegative = QtGui.QRadioButton(self.layoutWidget3)
        self.radioSkewnessNegative.setObjectName(_fromUtf8("radioSkewnessNegative"))
        self.horizontalLayout_3.addWidget(self.radioSkewnessNegative)
        self.radioSkewnessNone = QtGui.QRadioButton(self.layoutWidget3)
        self.radioSkewnessNone.setChecked(True)
        self.radioSkewnessNone.setObjectName(_fromUtf8("radioSkewnessNone"))
        self.horizontalLayout_3.addWidget(self.radioSkewnessNone)
        self.checkBoxXOR = QtGui.QCheckBox(self.tab_2)
        self.checkBoxXOR.setGeometry(QtCore.QRect(20, 300, 61, 22))
        self.checkBoxXOR.setObjectName(_fromUtf8("checkBoxXOR"))
        self.cmbConnections = QtGui.QComboBox(self.tab_2)
        self.cmbConnections.setGeometry(QtCore.QRect(719, 49, 261, 27))
        self.cmbConnections.setObjectName(_fromUtf8("cmbConnections"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(719, 279, 261, 171))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.anisotropyChexkBox = QtGui.QCheckBox(self.groupBox_2)
        self.anisotropyChexkBox.setGeometry(QtCore.QRect(1, 31, 49, 23))
        self.anisotropyChexkBox.setObjectName(_fromUtf8("anisotropyChexkBox"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(1, 60, 261, 120))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_21 = QtGui.QLabel(self.layoutWidget_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_6.addWidget(self.label_21)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.directionSlider = QtGui.QSlider(self.layoutWidget_2)
        self.directionSlider.setEnabled(False)
        self.directionSlider.setMaximum(180)
        self.directionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.directionSlider.setObjectName(_fromUtf8("directionSlider"))
        self.horizontalLayout_4.addWidget(self.directionSlider)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_23 = QtGui.QLabel(self.layoutWidget_2)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_5.addWidget(self.label_23)
        self.label_25 = QtGui.QLabel(self.layoutWidget_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_5.addWidget(self.label_25)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_22 = QtGui.QLabel(self.layoutWidget_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_7.addWidget(self.label_22)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ratioSlider = QtGui.QSlider(self.layoutWidget_2)
        self.ratioSlider.setEnabled(False)
        self.ratioSlider.setMaximum(100)
        self.ratioSlider.setSingleStep(1)
        self.ratioSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ratioSlider.setObjectName(_fromUtf8("ratioSlider"))
        self.horizontalLayout_6.addWidget(self.ratioSlider)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_24 = QtGui.QLabel(self.layoutWidget_2)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_7.addWidget(self.label_24)
        self.label_26 = QtGui.QLabel(self.layoutWidget_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_7.addWidget(self.label_26)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.groupAnisotropy = QtGui.QGroupBox(self.tab_2)
        self.groupAnisotropy.setEnabled(True)
        self.groupAnisotropy.setGeometry(QtCore.QRect(380, 20, 291, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupAnisotropy.setFont(font)
        self.groupAnisotropy.setCheckable(True)
        self.groupAnisotropy.setChecked(False)
        self.groupAnisotropy.setObjectName(_fromUtf8("groupAnisotropy"))
        self.label_27 = QtGui.QLabel(self.groupAnisotropy)
        self.label_27.setGeometry(QtCore.QRect(3, 42, 131, 17))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.layoutWidget4 = QtGui.QWidget(self.groupAnisotropy)
        self.layoutWidget4.setGeometry(QtCore.QRect(4, 67, 191, 31))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.sliderAnisotropyDirection = QtGui.QSlider(self.layoutWidget4)
        self.sliderAnisotropyDirection.setEnabled(False)
        self.sliderAnisotropyDirection.setMaximum(180)
        self.sliderAnisotropyDirection.setOrientation(QtCore.Qt.Horizontal)
        self.sliderAnisotropyDirection.setObjectName(_fromUtf8("sliderAnisotropyDirection"))
        self.horizontalLayout_8.addWidget(self.sliderAnisotropyDirection)
        self.lcdNumber = QtGui.QLCDNumber(self.layoutWidget4)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.horizontalLayout_8.addWidget(self.lcdNumber)
        self.label_29 = QtGui.QLabel(self.layoutWidget4)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_8.addWidget(self.label_29)
        self.label_30 = QtGui.QLabel(self.groupAnisotropy)
        self.label_30.setGeometry(QtCore.QRect(3, 106, 130, 17))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.layoutWidget5 = QtGui.QWidget(self.groupAnisotropy)
        self.layoutWidget5.setGeometry(QtCore.QRect(6, 132, 191, 31))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.sliderAnisotropyTolerance = QtGui.QSlider(self.layoutWidget5)
        self.sliderAnisotropyTolerance.setEnabled(False)
        self.sliderAnisotropyTolerance.setMaximum(100)
        self.sliderAnisotropyTolerance.setSingleStep(1)
        self.sliderAnisotropyTolerance.setOrientation(QtCore.Qt.Horizontal)
        self.sliderAnisotropyTolerance.setObjectName(_fromUtf8("sliderAnisotropyTolerance"))
        self.horizontalLayout_9.addWidget(self.sliderAnisotropyTolerance)
        self.lcdNumber_2 = QtGui.QLCDNumber(self.layoutWidget5)
        self.lcdNumber_2.setEnabled(False)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.horizontalLayout_9.addWidget(self.lcdNumber_2)
        self.label_32 = QtGui.QLabel(self.layoutWidget5)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_9.addWidget(self.label_32)
        self.qbSmoothingVectorField = QtGui.QGroupBox(self.tab_2)
        self.qbSmoothingVectorField.setGeometry(QtCore.QRect(10, 380, 351, 51))
        self.qbSmoothingVectorField.setObjectName(_fromUtf8("qbSmoothingVectorField"))
        self.label_10 = QtGui.QLabel(self.qbSmoothingVectorField)
        self.label_10.setGeometry(QtCore.QRect(190, 10, 153, 34))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.layoutWidget_4 = QtGui.QWidget(self.qbSmoothingVectorField)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 141, 26))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self._2 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self._2.setSpacing(6)
        self._2.setMargin(0)
        self._2.setObjectName(_fromUtf8("_2"))
        self.radioSmoothingYes = QtGui.QRadioButton(self.layoutWidget_4)
        self.radioSmoothingYes.setObjectName(_fromUtf8("radioSmoothingYes"))
        self._2.addWidget(self.radioSmoothingYes)
        self.radioSmoothingNo = QtGui.QRadioButton(self.layoutWidget_4)
        self.radioSmoothingNo.setChecked(True)
        self.radioSmoothingNo.setObjectName(_fromUtf8("radioSmoothingNo"))
        self._2.addWidget(self.radioSmoothingNo)
        self.barrierLayerListWidget = QtGui.QListWidget(self.tab_2)
        self.barrierLayerListWidget.setGeometry(QtCore.QRect(390, 260, 281, 181))
        self.barrierLayerListWidget.setObjectName(_fromUtf8("barrierLayerListWidget"))
        self.refreshBarrierListButton = QtGui.QPushButton(self.tab_2)
        self.refreshBarrierListButton.setGeometry(QtCore.QRect(390, 230, 121, 27))
        self.refreshBarrierListButton.setObjectName(_fromUtf8("refreshBarrierListButton"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(390, 210, 220, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tabDlg.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 321, 191))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.radioShapefile = QtGui.QRadioButton(self.groupBox_3)
        self.radioShapefile.setGeometry(QtCore.QRect(20, 30, 131, 23))
        self.radioShapefile.setObjectName(_fromUtf8("radioShapefile"))
        self.radioTextFile = QtGui.QRadioButton(self.groupBox_3)
        self.radioTextFile.setGeometry(QtCore.QRect(20, 60, 108, 23))
        self.radioTextFile.setChecked(True)
        self.radioTextFile.setObjectName(_fromUtf8("radioTextFile"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(370, 20, 271, 211))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.checkAttributeMean = QtGui.QCheckBox(self.groupBox_5)
        self.checkAttributeMean.setGeometry(QtCore.QRect(20, 30, 93, 23))
        self.checkAttributeMean.setChecked(False)
        self.checkAttributeMean.setObjectName(_fromUtf8("checkAttributeMean"))
        self.checkAttributeSorting = QtGui.QCheckBox(self.groupBox_5)
        self.checkAttributeSorting.setGeometry(QtCore.QRect(20, 60, 93, 23))
        self.checkAttributeSorting.setChecked(False)
        self.checkAttributeSorting.setObjectName(_fromUtf8("checkAttributeSorting"))
        self.checkAttributeAngle = QtGui.QCheckBox(self.groupBox_5)
        self.checkAttributeAngle.setGeometry(QtCore.QRect(20, 120, 93, 23))
        self.checkAttributeAngle.setChecked(True)
        self.checkAttributeAngle.setObjectName(_fromUtf8("checkAttributeAngle"))
        self.checkAttributeModule = QtGui.QCheckBox(self.groupBox_5)
        self.checkAttributeModule.setGeometry(QtCore.QRect(20, 150, 93, 23))
        self.checkAttributeModule.setChecked(True)
        self.checkAttributeModule.setObjectName(_fromUtf8("checkAttributeModule"))
        self.checkAttributeBestcase = QtGui.QCheckBox(self.groupBox_5)
        self.checkAttributeBestcase.setGeometry(QtCore.QRect(20, 180, 93, 23))
        self.checkAttributeBestcase.setObjectName(_fromUtf8("checkAttributeBestcase"))
        self.checkAttributeSkewness = QtGui.QCheckBox(self.groupBox_5)
        self.checkAttributeSkewness.setGeometry(QtCore.QRect(20, 90, 101, 23))
        self.checkAttributeSkewness.setChecked(False)
        self.checkAttributeSkewness.setObjectName(_fromUtf8("checkAttributeSkewness"))
        self.label_39 = QtGui.QLabel(self.tab_5)
        self.label_39.setGeometry(QtCore.QRect(380, 260, 301, 41))
        self.label_39.setStyleSheet(_fromUtf8("font: 10pt \"Arial\";"))
        self.label_39.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.buttonExportResults = QtGui.QPushButton(self.tab_5)
        self.buttonExportResults.setGeometry(QtCore.QRect(20, 270, 171, 28))
        self.buttonExportResults.setObjectName(_fromUtf8("buttonExportResults"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_7.setGeometry(QtCore.QRect(40, 110, 291, 91))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.radioSeparatorTab = QtGui.QRadioButton(self.groupBox_7)
        self.radioSeparatorTab.setGeometry(QtCore.QRect(10, 20, 54, 22))
        self.radioSeparatorTab.setChecked(True)
        self.radioSeparatorTab.setObjectName(_fromUtf8("radioSeparatorTab"))
        self.radioSeparatorComma = QtGui.QRadioButton(self.groupBox_7)
        self.radioSeparatorComma.setGeometry(QtCore.QRect(130, 20, 81, 22))
        self.radioSeparatorComma.setObjectName(_fromUtf8("radioSeparatorComma"))
        self.radioSeparatorSemilicon = QtGui.QRadioButton(self.groupBox_7)
        self.radioSeparatorSemilicon.setGeometry(QtCore.QRect(10, 50, 95, 22))
        self.radioSeparatorSemilicon.setObjectName(_fromUtf8("radioSeparatorSemilicon"))
        self.radioSeparatorOther = QtGui.QRadioButton(self.groupBox_7)
        self.radioSeparatorOther.setGeometry(QtCore.QRect(131, 53, 71, 22))
        self.radioSeparatorOther.setObjectName(_fromUtf8("radioSeparatorOther"))
        self.lineSeparatorOther = QtGui.QLineEdit(self.groupBox_7)
        self.lineSeparatorOther.setEnabled(False)
        self.lineSeparatorOther.setGeometry(QtCore.QRect(208, 51, 62, 27))
        self.lineSeparatorOther.setObjectName(_fromUtf8("lineSeparatorOther"))
        self.tabDlg.addTab(self.tab_5, _fromUtf8(""))
        self.buttonCompute = QtGui.QPushButton(pygisedtrend)
        self.buttonCompute.setGeometry(QtCore.QRect(10, 540, 171, 41))
        self.buttonCompute.setObjectName(_fromUtf8("buttonCompute"))

        self.retranslateUi(pygisedtrend)
        self.tabDlg.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), pygisedtrend.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), pygisedtrend.reject)
        QtCore.QObject.connect(self.sliderAnisotropyDirection, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber.display)
        QtCore.QObject.connect(self.groupAnisotropy, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sliderAnisotropyDirection.setEnabled)
        QtCore.QObject.connect(self.groupAnisotropy, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sliderAnisotropyTolerance.setEnabled)
        QtCore.QObject.connect(self.sliderAnisotropyTolerance, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_2.display)
        QtCore.QObject.connect(self.radioSeparatorOther, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineSeparatorOther.setEnabled)
        QtCore.QObject.connect(self.radioTextFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_7.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(pygisedtrend)

    def retranslateUi(self, pygisedtrend):
        pygisedtrend.setWindowTitle(_translate("pygisedtrend", "pygisedtrend", None))
        self.label_2.setText(_translate("pygisedtrend", "GiSedTrend", None))
        self.label_3.setText(_translate("pygisedtrend", "Version 2.5 (Juin 2014)", None))
        self.label_4.setText(_translate("pygisedtrend", "<html><head/><body><p><span style=\" font-weight:600;\">Emmanuel Poizot </span>(<A HREF=\"mailto:emmanuel.poizot@cnam.fr\">emmanuel.poizot@cnam.fr</A>)</p></body></html>", None))
        self.label_5.setText(_translate("pygisedtrend", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Contact:</span></p></body></html>", None))
        self.label_6.setText(_translate("pygisedtrend", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Web site: </span><a href=\" http://www.geoceano.fr\"><span style=\" font-style:italic; text-decoration: underline; color:#0000ff;\">http://www.geoceano.fr</span></a></p></body></html>", None))
        self.tabDlg.setTabText(self.tabDlg.indexOf(self.tab), _translate("pygisedtrend", "GiSedTrend", None))
        self.groupBox_6.setTitle(_translate("pygisedtrend", "Select data from...", None))
        self.pushButtonTextFile.setText(_translate("pygisedtrend", " Texte file...", None))
        self.GSTATemporaryLayerButton.setText(_translate("pygisedtrend", "From previous GSTA temporary layer", None))
        self.pushButtonDeteleRow.setText(_translate("pygisedtrend", "Delete line", None))
        self.label_11.setText(_translate("pygisedtrend", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Dataset</span></p></body></html>", None))
        self.pushButtonShapefile.setText(_translate("pygisedtrend", "Shapefile...", None))
        self.tabDlg.setTabText(self.tabDlg.indexOf(self.tab_3), _translate("pygisedtrend", "Data", None))
        self.label_7.setText(_translate("pygisedtrend", "Characteristic distance", None))
        self.groupBox.setTitle(_translate("pygisedtrend", "Trend case(s) to study", None))
        self.caseListEdit.setHtml(_translate("pygisedtrend", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.buttonRemoveTrendCase.setText(_translate("pygisedtrend", ">>", None))
        self.buttonAddTrendCase.setText(_translate("pygisedtrend", "<<", None))
        self.trendMean.setTitle(_translate("pygisedtrend", "Mean", None))
        self.trendSorting.setTitle(_translate("pygisedtrend", "Sorting", None))
        self.trendSkewness.setTitle(_translate("pygisedtrend", "Skewness", None))
        self.radioMeanFiner.setText(_translate("pygisedtrend", "F", None))
        self.radioMeanCoarser.setText(_translate("pygisedtrend", "C", None))
        self.radioMeanNone.setText(_translate("pygisedtrend", "None", None))
        self.radioSortingBetter.setText(_translate("pygisedtrend", "B", None))
        self.radioSortingPorer.setText(_translate("pygisedtrend", "P", None))
        self.radioSortingNone.setText(_translate("pygisedtrend", "None", None))
        self.radioSkewnessPositive.setText(_translate("pygisedtrend", "+", None))
        self.radioSkewnessNegative.setText(_translate("pygisedtrend", "-", None))
        self.radioSkewnessNone.setText(_translate("pygisedtrend", "None", None))
        self.checkBoxXOR.setText(_translate("pygisedtrend", "XOR", None))
        self.groupBox_2.setTitle(_translate("pygisedtrend", "Anisotropy", None))
        self.anisotropyChexkBox.setText(_translate("pygisedtrend", "Set", None))
        self.label_21.setText(_translate("pygisedtrend", "Direction (Degrees)", None))
        self.label_23.setText(_translate("pygisedtrend", "0", None))
        self.label_25.setText(_translate("pygisedtrend", "°", None))
        self.label_22.setText(_translate("pygisedtrend", "Tolerance (Percent)", None))
        self.label_24.setText(_translate("pygisedtrend", "0", None))
        self.label_26.setText(_translate("pygisedtrend", "%", None))
        self.groupAnisotropy.setTitle(_translate("pygisedtrend", "Anisotropy", None))
        self.label_27.setText(_translate("pygisedtrend", "Direction (Degrees)", None))
        self.label_29.setText(_translate("pygisedtrend", "°", None))
        self.label_30.setText(_translate("pygisedtrend", "Tolerance (Percent)", None))
        self.label_32.setText(_translate("pygisedtrend", "%", None))
        self.qbSmoothingVectorField.setTitle(_translate("pygisedtrend", "Smoothing vector field", None))
        self.label_10.setText(_translate("pygisedtrend", "Nota: Care must be\n"
"taken when smoothing.", None))
        self.radioSmoothingYes.setToolTip(_translate("pygisedtrend", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Smoothing the vector field.</p></body></html>", None))
        self.radioSmoothingYes.setWhatsThis(_translate("pygisedtrend", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If checked, the final vector field will be smoothing based on the characteristical distance defined. Care must be taken to perform this smoothing, in particular if the characteristical distance has been defined through a variographic study, in which case no smoothing should be performed.</p></body></html>", None))
        self.radioSmoothingYes.setText(_translate("pygisedtrend", "Yes", None))
        self.radioSmoothingNo.setToolTip(_translate("pygisedtrend", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal; text-decoration:none;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">No smoothing of the vector field (recommended).</p></body></html>", None))
        self.radioSmoothingNo.setText(_translate("pygisedtrend", "No", None))
        self.refreshBarrierListButton.setText(_translate("pygisedtrend", "Refresh the list", None))
        self.label_8.setText(_translate("pygisedtrend", "Select layer(s) to use as barrier(s)", None))
        self.tabDlg.setTabText(self.tabDlg.indexOf(self.tab_2), _translate("pygisedtrend", "Settings", None))
        self.groupBox_3.setTitle(_translate("pygisedtrend", "Select results file format output", None))
        self.radioShapefile.setText(_translate("pygisedtrend", "Shapefile (ESRI)", None))
        self.radioTextFile.setText(_translate("pygisedtrend", "Text (*.txt)", None))
        self.groupBox_5.setTitle(_translate("pygisedtrend", "Select attributes to export", None))
        self.checkAttributeMean.setText(_translate("pygisedtrend", "Mean", None))
        self.checkAttributeSorting.setText(_translate("pygisedtrend", "Sorting", None))
        self.checkAttributeAngle.setText(_translate("pygisedtrend", "Angle", None))
        self.checkAttributeModule.setText(_translate("pygisedtrend", "Module", None))
        self.checkAttributeBestcase.setText(_translate("pygisedtrend", "Best case", None))
        self.checkAttributeSkewness.setText(_translate("pygisedtrend", "Skewness", None))
        self.label_39.setText(_translate("pygisedtrend", "Nota:\n"
"Coordinates of points will be automatically export", None))
        self.buttonExportResults.setText(_translate("pygisedtrend", "Export...", None))
        self.groupBox_7.setTitle(_translate("pygisedtrend", "Field separator", None))
        self.radioSeparatorTab.setText(_translate("pygisedtrend", "Tab", None))
        self.radioSeparatorComma.setText(_translate("pygisedtrend", "Comma", None))
        self.radioSeparatorSemilicon.setText(_translate("pygisedtrend", "Semilicon", None))
        self.radioSeparatorOther.setText(_translate("pygisedtrend", "Other", None))
        self.tabDlg.setTabText(self.tabDlg.indexOf(self.tab_5), _translate("pygisedtrend", "Outputs", None))
        self.buttonCompute.setText(_translate("pygisedtrend", "Compute", None))

import resources_rc
